In [31]:
import numpy as np

# Basic Vector and Matrix Operation with Numpy
# Problem - 1: Array Creation:

# task1
arr = np.empty((2, 2))
print(arr)

# task2
print("-" * 50)
arr = np.ones((4, 2))
print(arr)

# task3
print("-" * 50)
arr = np.full((3, 3), dtype=int ,fill_value=99)
print(arr)

# task4
print("-" * 50)
arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

# task5
print("-" * 50)
arr = np.array([[1, 2, 3], [4, 5, 6]])
ones_arr = np.ones_like(arr)
print(ones_arr)

# task6
print("-" * 50)
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)


[[0. 0.]
 [0. 0.]]
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------------------------------------
[[99 99 99]
 [99 99 99]
 [99 99 99]]
--------------------------------------------------
[[0 0 0]
 [0 0 0]]
--------------------------------------------------
[[1 1 1]
 [1 1 1]]
--------------------------------------------------
[1 2 3 4]


In [71]:
import numpy as np

# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

# task1
arr = np.arange(10,50)
print(arr)

# task2
print("-" * 50)
arr = np.arange(0, 9)
reshaped_arr = np.reshape(arr, (3,3))
print(reshaped_arr)

# task3
print("-" * 50)
identity_matrix = np.eye(3)
print(identity_matrix)

# task4
print("-" * 50)
random_number_arr = np.random.random(30)
mean = random_number_arr.mean()
print(mean)

# task5
print("-" * 50)
arr = np.random.random((10,10))
min_value = arr.min()
max_value = arr.max()
print(min_value, max_value)

# task6
print("-" * 50)
arr = np.zeros(10)
arr[4] = 1
print(arr)

# task7
print("-" * 50)
arr = [1,2,0,0,4,0]
reversed_arr = np.flip(arr)
print(reversed_arr)

# task8
print("-" * 50)
rows, cols = 5, 5
arr = np.zeros((rows, cols), dtype=int)
arr[0, :] = 1   #first row, all columns
arr[-1, :] = 1  #last row, all columns
arr[:, 0] = 1   #all rows, first columns
arr[:, -1] = 1  #all rows, last columns
print(arr)

# task9
print("-" * 50)
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1 #odd rows but even columns
checkerboard[::2, 1::2] = 1 #even rows but odd columns
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
--------------------------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------------
0.4031638379357821
--------------------------------------------------
0.002855456548963242 0.9915744018148415
--------------------------------------------------
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
--------------------------------------------------
[0 4 0 0 2 1]
--------------------------------------------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
--------------------------------------------------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [99]:
import numpy as np

# Problem - 3: Array Operations:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

# task1
sum_xy = np.add(x,y)
sum_vw = np.add(v,w)
print(sum_xy, sum_vw)

# task2
print("-" * 50)
subtract_xy = np.subtract(x,y)
subtract_vw = np.subtract(v,w)
print(subtract_xy, subtract_vw)

# task3
print("-" * 50)
multiply_x = np.multiply(x, 2)
multiply_y = np.multiply(y, 3)
multiply_v = np.multiply(v, 4)
multiply_w = np.multiply(w, 5)
print(multiply_x, multiply_y, multiply_v, multiply_w)

# task4
print("-" * 50)
x_squared = np.square(x)
y_squared = np.square(y)
v_squared = np.square(v)
w_squared = np.square(w)
print(x_squared, y_squared, v_squared, w_squared)

# task5
print("-" * 50)
dot_product_xy = np.dot(x,y)
dot_product_vw = np.dot(v,w)
print(dot_product_xy, dot_product_vw)

# task6
print("-" * 50)
concat_xy_row = np.concatenate((x,y), axis=0)
concat_vw_col = np.vstack((v, w)) # no need for stating axis=1 as vstack vertically stacks its itself
print(concat_xy_row)
print(concat_vw_col)

# task7
# concat_xv = np.concatenate((x,v))
# print(concat_xv)
# Error occurs here because x is a 2D array and v is a 1D array and numpy cannot concatenate arrays with mismatched dimensions.

[[ 6  8]
 [10 13]] [20 22]
--------------------------------------------------
[[-4 -4]
 [-4 -3]] [-2 -2]
--------------------------------------------------
[[ 2  4]
 [ 6 10]] [[15 18]
 [21 24]] [36 40] [55 60]
--------------------------------------------------
[[ 1  4]
 [ 9 25]] [[25 36]
 [49 64]] [ 81 100] [121 144]
--------------------------------------------------
[[19 22]
 [50 58]] 219
--------------------------------------------------
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [110]:
import numpy as np

# Problem - 4: Matrix Operations:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# task1
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A inverse:\n", A_inv)
print("A · A_inv:\n", I)
print(np.allclose(I, np.identity(2)))

# task2
print("-" * 50)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("A · B:\n", AB)
print("B · A:\n", BA)
print(np.allclose(AB, BA))

# task3
print("-" * 50)
AB = np.dot(A, B)
AB_transpose = AB.T
BT_AT = np.dot(B.T, B.T)
print("(AB)T:\n", AB_transpose)
print("BT · AT:\n", BT_AT)
print(np.array_equal(AB_transpose, BT_AT))

# task4 and 5
print("-" * 50)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A · A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
True
--------------------------------------------------
A · B:
 [[23 13]
 [51 29]]
B · A:
 [[36 44]
 [13 16]]
False
--------------------------------------------------
(AB)T:
 [[23 51]
 [13 29]]
BT · AT:
 [[31 12]
 [18  7]]
False
--------------------------------------------------
[[ 2.]
 [ 1.]
 [-2.]]


In [119]:
import numpy as np
import time

# 4.2 Experiment: How Fast is Numpy?
#1. Element-wise Addition:
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("time taken by python list:", end_time - start_time, "seconds")

arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
print("time taken by numpy array:", end_time - start_time, "seconds")

#2. Element-wise Multiplication:
print("-" * 50)
list1 = list(range(1000000))
list2 = list(range(1000000))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
print("time taken by python list:", end_time - start_time, "seconds")

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_np = arr1 * arr2
end_time = time.time()
print("time taken by numpy array:", end_time - start_time, "seconds")

#3. Dot Product
print("-" * 50)

#using python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
print("dot product by python lists:", dot_list)
print("time taken by python lists:", end_time - start_time, "seconds")

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# using numpy
start_time = time.time()
dot_np = np.dot(arr1, arr2)
end_time = time.time()
print("dot product by numpy", dot_np)
print("time taken by numpy:", end_time - start_time, "seconds")

#4. Matrix Multiplication
print("-" * 50)
size = 1000

# using python lists
A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]
result = [[0 for _ in range(size)] for _ in range(size)]
start = time.time()
for i in range(size):
    for j in range(size):
        total = 0
        for k in range(size):
            total += A[i][k] * B[k][j]
        result[i][j] = total
end = time.time()
print("time taken by python lists:", end - start, "seconds")

# using numpy
A_np = np.ones((size, size))
B_np = np.ones((size, size))
start = time.time()
np.dot(A_np, B_np)
end = time.time()
print("time taken by numpy:", end - start, "seconds")




time taken by python list: 0.13570928573608398 seconds
time taken by numpy array: 0.002360105514526367 seconds
--------------------------------------------------
time taken by python list: 0.11666297912597656 seconds
time taken by numpy array: 0.002318859100341797 seconds
--------------------------------------------------
dot product by python lists: 333332833333500000
time taken by python lists: 0.10397648811340332 seconds
dot product by numpy 333332833333500000
time taken by numpy: 0.00197601318359375 seconds
--------------------------------------------------


KeyboardInterrupt: 